const contractOptions = [
  {
    value: 'full_time',
    label: 'Повна',
  },
  {
    value: 'part_time',
    label: 'Неповна',
  },
];

const educationOptions = [
  {
    label: 'Базова середня освіта',
    value: 'basic_general',
  },
  {
    label: 'Повна загальна середня освіта',
    value: 'complete_general',
  },
  {
    label: 'Фахова передвища освіта',
    value: 'junior_bachelor',
  },
  {
    label: 'Бакалавр',
    value: 'bachelor',
  },
  {
    label: 'Магістер',
    value: 'master',
  },
  {
    label: 'Доктор філософії/доктор мистецтва',
    value: 'doctor_philosophy_arts',
  },
  {
    label: 'Доктор наук',
    value: 'doctor_sciences',
  },
];

const SALARY_VALUE = '1';
const SALARY_RANGE = '2';

const salaryOptions = [
  {
    value: SALARY_VALUE,
    label: 'Значення',
  },
  {
    value: SALARY_RANGE,
    label: 'Діапазон',
  },
];

const levelOptions = [
  {
    value: 'A1',
    label: 'A1',
  },
  {
    value: 'A2',
    label: 'A2',
  },
  {
    value: 'B1',
    label: 'B1',
  },
  {
    value: 'B2',
    label: 'B2',
  },
  {
    value: 'C1',
    label: 'C1',
  },
  {
    value: 'C2',
    label: 'C2',
  },
];

const languageOptions = [
  { value: 'en', label: 'Англійська' },
  { value: 'es', label: 'Іспанська' },
  { value: 'it', label: 'Італійська' },
  { value: 'zh', label: 'Китайська' },
  { value: 'ko', label: 'Корейська' },
  { value: 'de', label: 'Німецька' },
  { value: 'pl', label: 'Польська' },
  { value: 'uk', label: 'Українська' },
  { value: 'fr', label: 'Французька' },

  { value: 'ab', label: 'Абхазька' },
  { value: 'av', label: 'Аварська' },
  { value: 'ae', label: 'Авестійська' },
  { value: 'az', label: 'Азербайджанська' },
  { value: 'ay', label: 'Аймара' },
  { value: 'ak', label: 'Аканська' },
  { value: 'sq', label: 'Албанська' },
  { value: 'am', label: 'Амхарська' },
  { value: 'ar', label: 'Арабська' },
  { value: 'an', label: 'Арагонська' },
  { value: 'as', label: 'Ассамська' },
  { value: 'om', label: 'Афан/Оромо/Одіа' },
  { value: 'aa', label: 'Афарська' },
  { value: 'af', label: 'Африкаанс' },
  { value: 'bm', label: 'Бамбарська' },
  { value: 'eu', label: 'Баскська' },
  { value: 'ba', label: 'Башкирська' },
  { value: 'bn', label: 'Бенгальська' },
  { value: 'bg', label: 'Болгарська' },
  { value: 'bs', label: 'Боснійська' },
  { value: 'br', label: 'Бретонська' },
  { value: 'dz', label: 'Бхутанська' },
  { value: 'be', label: 'Білоруська' },
  { value: 'my', label: 'Бірманська' },
  { value: 'bi', label: 'Біслама' },
  { value: 'bh', label: 'Біхарі' },
  { value: 'vi', label: "В'єтнамська" },
  { value: 'wa', label: 'Валлонська' },
  { value: 'cy', label: 'Валлійська' },
  { value: 've', label: 'Венда' },
  { value: 'vo', label: 'Волапюк' },
  { value: 'wo', label: 'Волоф' },
  { value: 'hy', label: 'Вірменська' },
  { value: 'gl', label: 'Галісійська' },
  { value: 'lg', label: 'Ганда' },
  { value: 'ht', label: 'Гаїтянська креольська' },
  { value: 'hz', label: 'Гереро' },
  { value: 'nl', label: 'Голландська' },
  { value: 'kl', label: 'Гренландська' },
  { value: 'el', label: 'Грецька' },
  { value: 'ka', label: 'Грузинська' },
  { value: 'gn', label: 'Гуарані' },
  { value: 'gu', label: 'Гуджараті' },
  { value: 'hi', label: 'Гінді' },
  { value: 'da', label: 'Данська' },
  { value: 'ee', label: 'Еве' },
  { value: 'eo', label: 'Есперанто' },
  { value: 'et', label: 'Естонська' },
  { value: 'zu', label: 'Зулуська' },
  { value: 'he', label: 'Іврит' },
  { value: 'iw', label: 'Іврит' },
  { value: 'ig', label: 'Ігбо' },
  { value: 'ji', label: 'Ідиш' },
  { value: 'yi', label: 'Ідиш' },
  { value: 'io', label: 'Ідо' },
  { value: 'id', label: 'Індонезійська' },
  { value: 'ia', label: 'Інтерлінгва' },
  { value: 'ie', label: 'Інтерлінгве' },
  { value: 'iu', label: 'Інуктитут' },
  { value: 'ik', label: 'Інупіак' },
  { value: 'ga', label: 'Ірландська' },
  { value: 'is', label: 'Ісландська' },
  { value: 'yo', label: 'Йоруба' },
  { value: 'kk', label: 'Казахська' },
  { value: 'kn', label: 'Каннада' },
  { value: 'kr', label: 'Канурі' },
  { value: 'ca', label: 'Каталонська' },
  { value: 'ks', label: 'Кашмірська' },
  { value: 'qu', label: 'Кетчуа' },
  { value: 'ky', label: 'Киргизька' },
  { value: 'kv', label: 'Комі' },
  { value: 'kg', label: 'Конго' },
  { value: 'kok', label: 'Конкані' },
  { value: 'kw', label: 'Корнська' },
  { value: 'co', label: 'Корсиканська' },
  { value: 'xh', label: 'Коса' },
  { value: 'cr', label: 'Крі' },
  { value: 'kj', label: 'Куаньяма' },
  { value: 'ku', label: 'Курдська' },
  { value: 'km', label: 'Кхмерська' },
  { value: 'ki', label: 'Кікуйю' },
  { value: 'rw', label: 'Кіньяруанда' },
  { value: 'rn', label: 'Кірундійська' },
  { value: 'lo', label: 'Лаоська' },
  { value: 'la', label: 'Латинська' },
  { value: 'lv', label: 'Латиська' },
  { value: 'lt', label: 'Литовська' },
  { value: 'lu', label: 'Луба-Катанга' },
  { value: 'lb', label: 'Люксембурзька' },
  { value: 'li', label: 'Лімбургійська' },
  { value: 'ln', label: 'Лінгала' },
  { value: 'mk', label: 'Македонська' },
  { value: 'mg', label: 'Малагасійська' },
  { value: 'ms', label: 'Малайська' },
  { value: 'ml', label: 'Малаялам' },
  { value: 'dv', label: 'Мальдівська' },
  { value: 'mt', label: 'Мальтійська' },
  { value: 'mi', label: 'Маорі' },
  { value: 'mr', label: 'Маратхі' },
  { value: 'mh', label: 'Маршалльська' },
  { value: 'gv', label: 'Менська' },
  { value: 'mo', label: 'Молдовська' },
  { value: 'mn', label: 'Монгольська' },
  { value: 'nv', label: 'Навахо' },
  { value: 'na', label: 'Науру' },
  { value: 'ng', label: 'Ндонга' },
  { value: 'ne', label: 'Непальська (Індія)' },
  { value: 'no', label: 'Норвезька' },
  { value: 'nb', label: 'Норвезька (Букмол)' },
  { value: 'nn', label: 'Норвезька (Нюнорск)' },
  { value: 'oj', label: 'Оджибва' },
  { value: 'or', label: 'Одіа' },
  { value: 'oc', label: 'Окситанська' },
  { value: 'os', label: 'Осетинська' },
  { value: 'pi', label: 'Палі' },
  { value: 'pa', label: 'Панджабі' },
  { value: 'fa', label: 'Перська' },
  { value: 'pt', label: 'Португальська' },
  { value: 'ps', label: 'Пушту' },
  { value: 'nr', label: 'Південна ндебеле' },
  { value: 'nd', label: 'Північна ндебеле' },
  { value: 'ns', label: 'Північний сото' },
  { value: 'rm', label: 'Ретороманська' },
  { value: 'ru', label: 'Російська' },
  { value: 'ro', label: 'Румунська' },
  { value: 'se', label: 'Саамська' },
  { value: 'sm', label: 'Самоанська' },
  { value: 'sg', label: 'Санго' },
  { value: 'sa', label: 'Санскрит' },
  { value: 'sc', label: 'Сардинська' },
  { value: 'ss', label: 'Сваті' },
  { value: 'sr', label: 'Сербська' },
  { value: 'sh', label: 'Сербсько-хорватська' },
  { value: 'st', label: 'Сесото' },
  { value: 'tn', label: 'Сетсвана' },
  { value: 'si', label: 'Сингальська' },
  { value: 'syr', label: 'Сирійська' },
  { value: 'ii', label: 'Сичуань І' },
  { value: 'sk', label: 'Словацька' },
  { value: 'ls', label: 'Словенська' },
  { value: 'so', label: 'Сомалійська' },
  { value: 'sb', label: 'Сорбська' },
  { value: 'cu', label: "Старослов'янська" },
  { value: 'sw', label: 'Суахілі' },
  { value: 'su', label: 'Суданська' },
  { value: 'sx', label: 'Суту' },
  { value: 'sd', label: 'Сіндхі' },
  { value: 'tl', label: 'Тагальська' },
  { value: 'tg', label: 'Таджицька' },
  { value: 'th', label: 'Тайська' },
  { value: 'ta', label: 'Тамільська' },
  { value: 'tt', label: 'Татарська' },
  { value: 'ty', label: 'Таїтянська' },
  { value: 'tw', label: 'Тві' },
  { value: 'te', label: 'Телугу' },
  { value: 'bo', label: 'Тибетська' },
  { value: 'ti', label: 'Тигринья' },
  { value: 'to', label: 'Тонганська' },
  { value: 'ts', label: 'Тсонга' },
  { value: 'tr', label: 'Турецька' },
  { value: 'tk', label: 'Туркменська' },
  { value: 'hu', label: 'Угорська' },
  { value: 'uz', label: 'Узбецька' },
  { value: 'ug', label: 'Уйгурська' },
  { value: 'ur', label: 'Урду' },
  { value: 'fo', label: 'Фарерська' },
  { value: 'fy', label: 'Фризька' },
  { value: 'ff', label: 'Фульфульде' },
  { value: 'fj', label: 'Фіджійська' },
  { value: 'fi', label: 'Фінська' },
  { value: 'ha', label: 'Хауса' },
  { value: 'hr', label: 'Хорватська' },
  { value: 'ho', label: 'Хірі моту' },
  { value: 'ch', label: 'Чаморро' },
  { value: 'cs', label: 'Чеська' },
  { value: 'ce', label: 'Чеченська' },
  { value: 'za', label: 'Чжуан' },
  { value: 'cv', label: 'Чуваська' },
  { value: 'ny', label: 'Чічева' },
  { value: 'sv', label: 'Шведська' },
  { value: 'sn', label: 'Шона' },
  { value: 'gd', label: 'Шотландська гельська' },
  { value: 'jv', label: 'Яванська' },
];

export { contractOptions, educationOptions, salaryOptions, SALARY_VALUE, SALARY_RANGE, levelOptions, languageOptions };
